### ISSUE TITLE
deduplicate() and extract_domain()

### ISSUE THREAD

**Issue by sebstier** [schochastics/webtrackR#97] opened 2023-12-09 17:03 UTC
Hi,

the new version of deduplicate() returns a data.frame instead of a wt_dt object. 

the new version of extract_domain() with the adaR implementation does not accept drop_na = FALSE anymore, but keeps all rows by default. That is intentional, right?

**Comment by schochastics** [comment] 2023-12-09 18:26
deduplicate is fixed now. 

The second was intentional, but probably should have a proper note. The reasons to drop the parameter are twofold:
1) adaR fails less (actually almost never) to parse the domain and
2) if we want to drop certain rows then we should write a proper filter function

**Comment by sebstier** [comment] 2023-12-09 20:53
Thanks. Two more points on extract_domain():

- Examples are still tailored towards the previous version
- extract_domain() only seems to extract a valid domain when a url starts with http/https. That is sometimes not the case, e.g. in WebTrack 2021 data.

**Comment by schochastics** [comment] 2023-12-10 19:16
The open pull request https://github.com/schochastics/webtrackR/pull/95 is going to deal with those issues. Just had no time to finalize it yet

**Comment by sebstier** [comment] 2023-12-11 11:35
two more issues: 

- deduplicate() creates two timestamp columns
- deduplicate() converts format of column timestamp from dttm to dbl

**Comment by schochastics** [comment] 2023-12-11 13:28
thanks, thats a bug. I will fix that in the open PR

**Comment by schochastics** [comment] 2023-12-11 18:22
@sebstier can you post  a snippet that produces this error? cannot reproduce it

**Closed** 2023-12-11 20:29 UTC
